name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true

      - name: Build
        run: yarn build

      - name: Deploy-Main
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          repo: Nu1LCTF/Nu1L-Team-Page-Main
          target_branch: master
          build_dir: build
          committer_name: Nu1l DevOps
          committer_email: devops@nu1l.com
          fqdn: nu1l.com
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT_FOR_NU1L }}

      - name: Deploy-Slave
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          repo: Nu1LCTF/Nu1L-Team-Page-Slave
          target_branch: master
          build_dir: build
          committer_name: Nu1l DevOps
          committer_email: devops@nu1l.com
          fqdn: nu1l-ctf.com
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT_FOR_NU1L }}

