name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true

      - name: Build
        run: yarn build

      - name: push
        uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: ${{ secrets.OSS_REGION }}
          access-key-id: ${{ secrets.OSS_ACCESS_ID }}
          access-key-secret: ${{ secrets.OSS_SECRET_KEY }}
      - run: ossutil cp ./build/ oss://${{ secrets.OSS_BUCKET }}/ --exclude "*.png" --exclude "*.jpg" -rf

